/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 hnair.com
 * All rights reserved.
 * ForumGroupDao.java
 * Date: 2012-10-17
 */
package com.epolleo.bp.forum.dao.ibatis;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import com.epolleo.bp.pub.AbstractDao;
import com.epolleo.bp.pub.PagingForm;
import com.epolleo.bp.pub.PagingResult;

import com.epolleo.bp.forum.bean.ForumGroupBean;

/**
 * <p>
 * 论坛版块的数据访问类
 * </p>
 * 
 * Date: 2012-10-17 下午04:15:17
 * 
 * @author Data Model Tool
 * @version 1.0
 */
public class ForumGroupDao extends AbstractDao<ForumGroupBean> {

    /**
     * @param entity
     *            新增论坛版块对象
     * @return 新增成功的论坛版块
     * @see ForumGroupBean
     */
    @Override
    public ForumGroupBean save(ForumGroupBean entity) {
        return save("insertForumGroup", entity);
    }

    /**
     * @param entityId
     *            待删除论坛版块的关键值（比如主键Key）
     * @return 如果删除成功，返回1
     */
    @Override
    public int delete(Serializable entityId) {
        return delete("deleteForumGroup", entityId);
    }

    /**
     * @param entity
     *            修改论坛版块对象
     * @return 如果修改成功，返回1
     * @see ForumGroupBean
     */
    @Override
    public int update(ForumGroupBean entity) {
        return update("updateForumGroup", entity);
    }

    /**
     * @param pagingForm
     *            分页及查询过滤参数
     * @return 指定页及条件的查询结果
     * @see PagingForm
     */
    @Override
    public PagingResult<ForumGroupBean> findPaging(PagingForm pagingParam,
        boolean fuzzy) {
        String sort = pagingParam.getSort();
        String order = pagingParam.getOrder();
        if (sort != null) {
            checkName(sort);
        }
        if (order != null) {
            checkName(order);
        }
        HashMap<String, Object> params = new HashMap<String, Object>();

        params.put("sort", pagingParam.getSort());
        params.put("order", pagingParam.getOrder());
        params.putAll(pagingParam.getFilter());
        ArrayList<ForumGroupBean> page = new ArrayList<ForumGroupBean>();
        int total = getSqlMapClientTemplate().queryForPage(page,
            "queryForumGroupPage", params, pagingParam.getSkip(),
            pagingParam.getPageSize());

        PagingResult<ForumGroupBean> result = new PagingResult<ForumGroupBean>(
            page, total);
        return result;
        // return findPaging("queryForumGroupPage", pagingForm, fuzzy);
    }

    /**
     * @return 查询论坛版块的所有记录
     * @see ForumGroupBean
     */
    @Override
    public List<ForumGroupBean> findAll() {
        return findAll("queryForumGroupList");
    }

    /**
     * @return 返回指定关键值（比如主键Key）的论坛版块
     * @see ForumGroupBean
     */
    @Override
    public ForumGroupBean find(Serializable id) {
        return find("queryForumGroupById", id);
    }

}