/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 epolleo.com
 * All rights reserved.
 * LocAction.java
 * Date: 2012-10-23
 */
package com.epolleo.bp.location.bean;

import java.util.Date;
/**
 * <p>地理区域表</p>
 * 
 * Date: 2012-10-23 14:04:58
 * 
 * @author 
 * @version 1.0
 */
public class LocBean {

    // 地理区域ID
    private Long locId;
    // 地理区域名称
    private String locName;
    // 地理区域备注
    private String locNote;
    // X坐标
    private Integer locX;
    // Y坐标
    private Integer locY;
    // 标识码
    private String locCode;
    // 状态
    private Boolean enable;
    // 创建人
    private String createUser;
    // 创建时间
    private Date createTime;
    // 更新人
    private String updateUser;
    // 更新时间
    private Date updateTime;
    public Long getLocId() {
        return locId;
    }
    public void setLocId(Long locId) {
        this.locId = locId;
    }
    public String getLocName() {
        return locName;
    }
    public void setLocName(String locName) {
        this.locName = locName;
    }
    public String getLocNote() {
        return locNote;
    }
    public void setLocNote(String locNote) {
        this.locNote = locNote;
    }
    public Integer getLocX() {
        return locX;
    }
    public void setLocX(Integer locX) {
        this.locX = locX;
    }
    public Integer getLocY() {
        return locY;
    }
    public void setLocY(Integer locY) {
        this.locY = locY;
    }
    public String getLocCode() {
        return locCode;
    }
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }
    public Boolean getEnable() {
        return enable;
    }
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }
    public String getCreateUser() {
        return createUser;
    }
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }
    public Date getCreateTime() {
        return createTime;
    }
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getUpdateUser() {
        return updateUser;
    }
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    public Date getUpdateTime() {
        return updateTime;
    }
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


}
