/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 epolleo.com
 * All rights reserved.
 * HolidayAction.java
 * Date: 2013-12-02
 */
package com.epolleo.bp.holiday.action;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;

import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.alibaba.citrus.turbine.Context;
import com.alibaba.citrus.turbine.dataresolver.Param;
import com.alibaba.citrus.turbine.dataresolver.Params;
import com.alibaba.citrus.turbine.util.Function;
import com.alibaba.citrus.turbine.util.FunctionDir;
import com.alibaba.citrus.turbine.util.FunctionName;

import com.epolleo.bp.util.DateUtils;
import com.epolleo.bp.pub.LoginUser;
import com.epolleo.bp.pub.PagingForm;
import com.epolleo.bp.pub.PagingResult;
import com.epolleo.bp.holiday.service.HolidayService;
import com.epolleo.bp.holiday.bean.HolidayBean;
import com.epolleo.bp.holiday.bean.HolidaySaveBean;

/**
 * <p>节假日管理的Action</p>
 * 
 * Date: 2013-12-02 下午01:36:49
 * 
 * @author TODO
 * @version 1.0
 */
@Function()
@FunctionDir(id="bp.holiday", name="工作日历")
public class HolidayAction {

    protected Logger logger = LoggerFactory.getLogger(getClass());

    @Resource
    private HolidayService service;

    /**
     * @param entity 新增节假日管理对象
     * @see Context
     * @see HolidayBean
     */
    @Function("bp.holiday.save")
    @FunctionName("工作日历保存")
    public void doSave(Context context, @Params HolidaySaveBean entity) {
        entity.setUpdateTime(DateUtils.getCurrentDate());
        entity.setUpdateUser(LoginUser.getCurrentUser().getUserId());
        service.saveDays(entity);
        context.put("json", entity);
    }

    /**
     * 根据日期查询当月的节假日
     * @param context
     * @param entity
     */
    @Function("bp.holiday.query")
    @FunctionName("工作日历查询")
    public void doQueryByDate(Context context,@Param(name = "startDay") String startDay,@Param(name = "endDay") String endDay) {
        Map<String,Object> filter= new HashMap<String,Object>();
        List<HolidayBean> result= null;
        if(StringUtils.isNotEmpty(startDay) && StringUtils.isNotEmpty(endDay)){
            filter.put("startDay", startDay);
            filter.put("endDay", endDay);
            result= service.queryByDate(filter);
        }else{
            result = new ArrayList<HolidayBean>();      
        }
        context.put("json", result);
    }
}