//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.20 at 11:00:33 ÉÏÎç CST 
//


package net.hna.dmt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.hna.dmt.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Schema_QNAME = new QName("http://www.hna.net/dmt/schema", "schema");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.hna.dmt.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sequence }
     * 
     */
    public Sequence createSequence() {
        return new Sequence();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link ForeignKey }
     * 
     */
    public ForeignKey createForeignKey() {
        return new ForeignKey();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Sheet }
     * 
     */
    public Sheet createSheet() {
        return new Sheet();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link Schema }
     * 
     */
    public Schema createSchema() {
        return new Schema();
    }

    /**
     * Create an instance of {@link Index }
     * 
     */
    public Index createIndex() {
        return new Index();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link TableRef }
     * 
     */
    public TableRef createTableRef() {
        return new TableRef();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Schema }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.hna.net/dmt/schema", name = "schema")
    public JAXBElement<Schema> createSchema(Schema value) {
        return new JAXBElement<Schema>(_Schema_QNAME, Schema.class, null, value);
    }

}
