//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.20 at 11:00:33 ÉÏÎç CST 
//


package net.hna.dmt.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VARCHAR"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="BOOLEAN"/>
 *     &lt;enumeration value="ENUM"/>
 *     &lt;enumeration value="NUMBER"/>
 *     &lt;enumeration value="CHAR"/>
 *     &lt;enumeration value="DATE"/>
 *     &lt;enumeration value="TIME"/>
 *     &lt;enumeration value="TIMESTAMP"/>
 *     &lt;enumeration value="BLOB"/>
 *     &lt;enumeration value="CLOB"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Type", namespace = "http://www.hna.net/dmt/schema")
@XmlEnum
public enum Type {

    VARCHAR,
    INTEGER,
    BOOLEAN,
    ENUM,
    NUMBER,
    CHAR,
    DATE,
    TIME,
    TIMESTAMP,
    BLOB,
    CLOB;

    public String value() {
        return name();
    }

    public static Type fromValue(String v) {
        return valueOf(v);
    }

}
