//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.20 at 11:00:33 ÉÏÎç CST 
//


package net.hna.dmt.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Vendor.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Vendor">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="oracle"/>
 *     &lt;enumeration value="mysql"/>
 *     &lt;enumeration value="sqlserver"/>
 *     &lt;enumeration value="db2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Vendor", namespace = "http://www.hna.net/dmt/schema")
@XmlEnum
public enum Vendor {

    @XmlEnumValue("oracle")
    ORACLE("oracle"),
    @XmlEnumValue("mysql")
    MYSQL("mysql"),
    @XmlEnumValue("sqlserver")
    SQLSERVER("sqlserver"),
    @XmlEnumValue("db2")
    DB_2("db2");
    private final String value;

    Vendor(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Vendor fromValue(String v) {
        for (Vendor c: Vendor.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
