spring:
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always
  jpa:
    database-platform: H2
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none