/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 epolleo.com
 * All rights reserved.
 * LocAction.java
 * Date: 2012-10-23
 */
package com.epolleo.bp.location.action;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.annotation.Resource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.alibaba.citrus.turbine.Context;
import com.alibaba.citrus.turbine.dataresolver.Param;
import com.alibaba.citrus.turbine.dataresolver.Params;
import com.alibaba.citrus.turbine.util.Function;
import com.alibaba.citrus.turbine.util.FunctionDir;
import com.alibaba.citrus.turbine.util.FunctionName;

import com.epolleo.bp.location.bean.LocBean;
import com.epolleo.bp.location.dao.LocDao;
import com.epolleo.bp.pub.LoginUser;
import com.epolleo.bp.pub.PagingForm;
import com.epolleo.bp.pub.PagingResult;
import com.epolleo.bp.seq.bean.IdKind;
import com.epolleo.bp.seq.dao.SeqDao;

/**
 * <p>
 * 地理区域表的Action
 * </p>
 * 
 * Date: 2012-10-23 下午02:07:57
 * 
 * @author TODO
 * @version 1.0
 */
@Function()
@FunctionDir(id="bp.loc", name="地理区域")
public class LocAction {

    protected Logger logger = LoggerFactory.getLogger(getClass());

    @Resource
    private LocDao tLocaltionDao;
    
    @Resource
    private SeqDao seqDao;

    /**
     * 处理指定页及条件的查询结果
     * 
     * @param form
     *            分页参数
     * @param entity
     *            查询过滤参数
     * @see Context
     * @see PagingForm
     * @see LocBean
     */
    @Function("bp.loc.query")
    @FunctionName("地理区域查询")
    public void doQuery(Context context, @Params PagingForm form,
        @Param(name = "page") Integer page, @Param(name = "rows") Integer rows,
        @Params LocBean entity) {
        if (page != null) {
            form.setPage(page);
        }
        if (rows != null) {
            form.setRows(rows);
        }
        PagingResult<LocBean> result = tLocaltionDao.findPaging(form,
            false);
        context.put("json", result);
    }
    
    @Function("bp.loc.query")
    public void doGetEnableLoc(Context context, @Params PagingForm form) {
    	List<LocBean> locations = tLocaltionDao.queryEnableLoc();
    	context.put("json", locations);
    }

    @Function("bp.loc.query")
    public void doQueryTree(Context context, @Params PagingForm form) {
        LocTree root = new LocTree();
        root.setId("-1");
        root.setText("全选");
        List<LocTree> children = new ArrayList<LocTree>();
        List<LocBean> locations = tLocaltionDao.findAll();
        for (LocBean location : locations) {
            children.add(new LocTree(location));
        }
        root.setChildren(children);
        root.setState("open");
        List<LocTree> locationResult = new ArrayList<LocTree>();
        locationResult.add(root);
        context.put("json", locationResult);
    }

    @Function("bp.loc.update")
    @FunctionName("地理区域更新")
    public void doUpdate(Context context, @Params PagingForm form,
        @Params LocBean entity) {
        Date now = new Date();
        String userId = LoginUser.getCurrentUser().getUserId();
        entity.setUpdateTime(now);
        entity.setUpdateUser(userId);
        tLocaltionDao.update(entity);
        context.put("json", entity);
    }

    @Function("bp.loc.save")
    @FunctionName("地理区域保存")
    public void doSave(Context context, @Params PagingForm form,
        @Params LocBean entity) {
        entity.setLocId(seqDao.getNewIdLong(IdKind.LocId));
        Date now = new Date();
        String userId = LoginUser.getCurrentUser().getUserId();
        entity.setCreateTime(now);
        entity.setCreateUser(userId);
        entity.setUpdateTime(now);
        entity.setUpdateUser(userId);
        tLocaltionDao.save(entity);
        context.put("json", entity);
    }

    @Function("bp.loc.delete")
    @FunctionName("地理区域删除")
    public void doDelete(Context context, @Params PagingForm form,
        @Param(name = "id") String id) {
        int delete = tLocaltionDao.delete(id);
        context.put("json", delete);
    }

    @Function("public")
    public void doQueryLocByIdcId(Context context,
        @Param(name = "idcId") String idcId) {
        LocBean result = tLocaltionDao.getLocByIdcId(idcId);
        context.put("json", result);
    }
}

class LocTree {
    private String id;
    private String text;
    private List<LocTree> children;
    private String state;

    public LocTree() {

    }

    public LocTree(LocBean locationBean) {
        this.id = locationBean.getLocId().toString();
        this.text = locationBean.getLocName();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public List<LocTree> getChildren() {
        return children;
    }

    public void setChildren(List<LocTree> children) {
        this.children = children;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

}