/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 epolleo.com
 * All rights reserved.
 * TaskDefAction.java
 * Date: 2012-11-10
 */
package com.epolleo.bp.task.bean;

import java.io.Serializable;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * <p>
 * 定时任务
 * </p>
 * 
 * Date: 2012-11-10 15:27:05
 * 
 * @version 1.0
 */
public class TaskDefBean implements Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = -4248453214398419788L;

    // 任务ID
    private int taskId;
    // 任务标识
    private String beanId;
    // 启停状态
    private boolean enable;
    // 任务名称
    private String taskName;
    // 启用时间
    private Date startTime;
    // 终止时间
    private Date endTime;
    // 定时方式
    private int shedType;
    // 定时设置
    private String shedExpr;
    // 执行标识
    private String execId;
    // 上次执行时间
    private Date lastTime;
    // 上次执行情况
    private String lastInfo;

    // 下次执行时间
    private Date nextTime;

    protected String updateUser;

    protected Date updateTime;
    
    public String bpId;

    /**
     * 获取属性taskId - "任务ID"的值.
     * 
     * @return 返回值是{@link int }
     * @see setTaskId
     */
    public int getTaskId() {
        return this.taskId;
    }

    /**
     * 设置属性taskId - "任务ID"的值.
     * 
     * @param taskId
     *            允许传入的值 是{@link int }
     * @see getTaskId
     */
    public void setTaskId(int taskId) {
        this.taskId = taskId;
    }

    /**
     * 获取属性beanId - "任务标识"的值.
     * 
     * @return 返回值是{@link String }
     * @see setBeanId
     */
    public String getBeanId() {
        return this.beanId;
    }

    /**
     * 设置属性beanId - "任务标识"的值.
     * 
     * @param beanId
     *            允许传入的值 是{@link String }
     * @see getBeanId
     */
    public void setBeanId(String beanId) {
        this.beanId = beanId;
    }

    /**
     * 获取属性enable - "启停状态"的值.
     * 
     * @return 返回值是{@link boolean }
     * @see setEnable
     */
    public boolean getEnable() {
        return this.enable;
    }

    /**
     * 设置属性enable - "启停状态"的值.
     * 
     * @param enable
     *            允许传入的值 是{@link boolean }
     * @see getEnable
     */
    public void setEnable(boolean enable) {
        this.enable = enable;
    }

    /**
     * 获取属性taskName - "任务名称"的值.
     * 
     * @return 返回值是{@link String }
     * @see setTaskName
     */
    public String getTaskName() {
        return this.taskName;
    }

    /**
     * 设置属性taskName - "任务名称"的值.
     * 
     * @param taskName
     *            允许传入的值 是{@link String }
     * @see getTaskName
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * 获取属性startTime - "启用时间"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setStartTime
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    public Date getStartTime() {
        return this.startTime;
    }

    /**
     * 设置属性startTime - "启用时间"的值.
     * 
     * @param startTime
     *            允许传入的值 是{@link Date }
     * @see getStartTime
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * 获取属性endTime - "终止时间"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setEndTime
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    public Date getEndTime() {
        return this.endTime;
    }

    /**
     * 设置属性endTime - "终止时间"的值.
     * 
     * @param endTime
     *            允许传入的值 是{@link Date }
     * @see getEndTime
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * 获取属性shedType - "定时方式"的值.
     * 
     * @return 返回值是{@link int }
     * @see setShedType
     */
    public int getShedType() {
        return this.shedType;
    }

    /**
     * 设置属性shedType - "定时方式"的值.
     * 
     * @param shedType
     *            允许传入的值 是{@link int }
     * @see getShedType
     */
    public void setShedType(int shedType) {
        this.shedType = shedType;
    }

    /**
     * 获取属性shedExpr - "定时设置"的值.
     * 
     * @return 返回值是{@link String }
     * @see setShedExpr
     */
    public String getShedExpr() {
        return this.shedExpr;
    }

    /**
     * 设置属性shedExpr - "定时设置"的值.
     * 
     * @param shedExpr
     *            允许传入的值 是{@link String }
     * @see getShedExpr
     */
    public void setShedExpr(String shedExpr) {
        this.shedExpr = shedExpr;
    }

    /**
     * @return the execId
     */
    public String getExecId() {
        return execId;
    }

    /**
     * @param execId the execId to set
     */
    public void setExecId(String execId) {
        this.execId = execId;
    }

    /**
     * 获取属性lastTime - "上次执行时间"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setLastTime
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    public Date getLastTime() {
        return this.lastTime;
    }

    /**
     * 设置属性lastTime - "上次执行时间"的值.
     * 
     * @param lastTime
     *            允许传入的值 是{@link Date }
     * @see getLastTime
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * 获取属性lastInfo - "上次执行情况"的值.
     * 
     * @return 返回值是{@link String }
     * @see setLastInfo
     */
    public String getLastInfo() {
        return this.lastInfo;
    }

    /**
     * 设置属性lastInfo - "上次执行情况"的值.
     * 
     * @param lastInfo
     *            允许传入的值 是{@link String }
     * @see getLastInfo
     */
    public void setLastInfo(String lastInfo) {
        this.lastInfo = lastInfo;
    }

    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    public Date getNextTime() {
        return nextTime;
    }

    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
