// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.java.world.dante.serializable.protobuf;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.google.protobuf.Timestamp birthday = 3;</code>
     */
    boolean hasBirthday();
    /**
     * <code>.google.protobuf.Timestamp birthday = 3;</code>
     */
    com.google.protobuf.Timestamp getBirthday();
    /**
     * <code>.google.protobuf.Timestamp birthday = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getBirthdayOrBuilder();

    /**
     * <code>string sex = 4;</code>
     */
    java.lang.String getSex();
    /**
     * <code>string sex = 4;</code>
     */
    com.google.protobuf.ByteString
        getSexBytes();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      sex_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (birthday_ != null) {
                subBuilder = birthday_.toBuilder();
              }
              birthday_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(birthday_);
                birthday_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              sex_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.java.world.dante.serializable.protobuf.UserProtos.User.class, org.java.world.dante.serializable.protobuf.UserProtos.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp birthday_;
    /**
     * <code>.google.protobuf.Timestamp birthday = 3;</code>
     */
    public boolean hasBirthday() {
      return birthday_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp birthday = 3;</code>
     */
    public com.google.protobuf.Timestamp getBirthday() {
      return birthday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthday_;
    }
    /**
     * <code>.google.protobuf.Timestamp birthday = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getBirthdayOrBuilder() {
      return getBirthday();
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private volatile java.lang.Object sex_;
    /**
     * <code>string sex = 4;</code>
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      }
    }
    /**
     * <code>string sex = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (birthday_ != null) {
        output.writeMessage(3, getBirthday());
      }
      if (!getSexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sex_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (birthday_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBirthday());
      }
      if (!getSexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.java.world.dante.serializable.protobuf.UserProtos.User)) {
        return super.equals(obj);
      }
      org.java.world.dante.serializable.protobuf.UserProtos.User other = (org.java.world.dante.serializable.protobuf.UserProtos.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasBirthday() != other.hasBirthday()) return false;
      if (hasBirthday()) {
        if (!getBirthday()
            .equals(other.getBirthday())) return false;
      }
      if (!getSex()
          .equals(other.getSex())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasBirthday()) {
        hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
        hash = (53 * hash) + getBirthday().hashCode();
      }
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.java.world.dante.serializable.protobuf.UserProtos.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.java.world.dante.serializable.protobuf.UserProtos.User.class, org.java.world.dante.serializable.protobuf.UserProtos.User.Builder.class);
      }

      // Construct using org.java.world.dante.serializable.protobuf.UserProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        if (birthdayBuilder_ == null) {
          birthday_ = null;
        } else {
          birthday_ = null;
          birthdayBuilder_ = null;
        }
        sex_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_User_descriptor;
      }

      @java.lang.Override
      public org.java.world.dante.serializable.protobuf.UserProtos.User getDefaultInstanceForType() {
        return org.java.world.dante.serializable.protobuf.UserProtos.User.getDefaultInstance();
      }

      @java.lang.Override
      public org.java.world.dante.serializable.protobuf.UserProtos.User build() {
        org.java.world.dante.serializable.protobuf.UserProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.java.world.dante.serializable.protobuf.UserProtos.User buildPartial() {
        org.java.world.dante.serializable.protobuf.UserProtos.User result = new org.java.world.dante.serializable.protobuf.UserProtos.User(this);
        result.id_ = id_;
        result.name_ = name_;
        if (birthdayBuilder_ == null) {
          result.birthday_ = birthday_;
        } else {
          result.birthday_ = birthdayBuilder_.build();
        }
        result.sex_ = sex_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.java.world.dante.serializable.protobuf.UserProtos.User) {
          return mergeFrom((org.java.world.dante.serializable.protobuf.UserProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.java.world.dante.serializable.protobuf.UserProtos.User other) {
        if (other == org.java.world.dante.serializable.protobuf.UserProtos.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasBirthday()) {
          mergeBirthday(other.getBirthday());
        }
        if (!other.getSex().isEmpty()) {
          sex_ = other.sex_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.java.world.dante.serializable.protobuf.UserProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.java.world.dante.serializable.protobuf.UserProtos.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp birthday_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> birthdayBuilder_;
      /**
       * <code>.google.protobuf.Timestamp birthday = 3;</code>
       */
      public boolean hasBirthday() {
        return birthdayBuilder_ != null || birthday_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 3;</code>
       */
      public com.google.protobuf.Timestamp getBirthday() {
        if (birthdayBuilder_ == null) {
          return birthday_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthday_;
        } else {
          return birthdayBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 3;</code>
       */
      public Builder setBirthday(com.google.protobuf.Timestamp value) {
        if (birthdayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          birthday_ = value;
          onChanged();
        } else {
          birthdayBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 3;</code>
       */
      public Builder setBirthday(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (birthdayBuilder_ == null) {
          birthday_ = builderForValue.build();
          onChanged();
        } else {
          birthdayBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 3;</code>
       */
      public Builder mergeBirthday(com.google.protobuf.Timestamp value) {
        if (birthdayBuilder_ == null) {
          if (birthday_ != null) {
            birthday_ =
              com.google.protobuf.Timestamp.newBuilder(birthday_).mergeFrom(value).buildPartial();
          } else {
            birthday_ = value;
          }
          onChanged();
        } else {
          birthdayBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 3;</code>
       */
      public Builder clearBirthday() {
        if (birthdayBuilder_ == null) {
          birthday_ = null;
          onChanged();
        } else {
          birthday_ = null;
          birthdayBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getBirthdayBuilder() {
        
        onChanged();
        return getBirthdayFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getBirthdayOrBuilder() {
        if (birthdayBuilder_ != null) {
          return birthdayBuilder_.getMessageOrBuilder();
        } else {
          return birthday_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : birthday_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp birthday = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getBirthdayFieldBuilder() {
        if (birthdayBuilder_ == null) {
          birthdayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getBirthday(),
                  getParentForChildren(),
                  isClean());
          birthday_ = null;
        }
        return birthdayBuilder_;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>string sex = 4;</code>
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sex = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sex = 4;</code>
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 4;</code>
       */
      public Builder clearSex() {
        
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>string sex = 4;</code>
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sex_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final org.java.world.dante.serializable.protobuf.UserProtos.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.java.world.dante.serializable.protobuf.UserProtos.User();
    }

    public static org.java.world.dante.serializable.protobuf.UserProtos.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.java.world.dante.serializable.protobuf.UserProtos.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .User user = 1;</code>
     */
    java.util.List<org.java.world.dante.serializable.protobuf.UserProtos.User> 
        getUserList();
    /**
     * <code>repeated .User user = 1;</code>
     */
    org.java.world.dante.serializable.protobuf.UserProtos.User getUser(int index);
    /**
     * <code>repeated .User user = 1;</code>
     */
    int getUserCount();
    /**
     * <code>repeated .User user = 1;</code>
     */
    java.util.List<? extends org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder> 
        getUserOrBuilderList();
    /**
     * <code>repeated .User user = 1;</code>
     */
    org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder getUserOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code UserList}
   */
  public  static final class UserList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserList)
      UserListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserList.newBuilder() to construct.
    private UserList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserList() {
      user_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                user_ = new java.util.ArrayList<org.java.world.dante.serializable.protobuf.UserProtos.User>();
                mutable_bitField0_ |= 0x00000001;
              }
              user_.add(
                  input.readMessage(org.java.world.dante.serializable.protobuf.UserProtos.User.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          user_ = java.util.Collections.unmodifiableList(user_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_UserList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_UserList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.java.world.dante.serializable.protobuf.UserProtos.UserList.class, org.java.world.dante.serializable.protobuf.UserProtos.UserList.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private java.util.List<org.java.world.dante.serializable.protobuf.UserProtos.User> user_;
    /**
     * <code>repeated .User user = 1;</code>
     */
    public java.util.List<org.java.world.dante.serializable.protobuf.UserProtos.User> getUserList() {
      return user_;
    }
    /**
     * <code>repeated .User user = 1;</code>
     */
    public java.util.List<? extends org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder> 
        getUserOrBuilderList() {
      return user_;
    }
    /**
     * <code>repeated .User user = 1;</code>
     */
    public int getUserCount() {
      return user_.size();
    }
    /**
     * <code>repeated .User user = 1;</code>
     */
    public org.java.world.dante.serializable.protobuf.UserProtos.User getUser(int index) {
      return user_.get(index);
    }
    /**
     * <code>repeated .User user = 1;</code>
     */
    public org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder getUserOrBuilder(
        int index) {
      return user_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < user_.size(); i++) {
        output.writeMessage(1, user_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < user_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.java.world.dante.serializable.protobuf.UserProtos.UserList)) {
        return super.equals(obj);
      }
      org.java.world.dante.serializable.protobuf.UserProtos.UserList other = (org.java.world.dante.serializable.protobuf.UserProtos.UserList) obj;

      if (!getUserList()
          .equals(other.getUserList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUserCount() > 0) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUserList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.java.world.dante.serializable.protobuf.UserProtos.UserList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserList)
        org.java.world.dante.serializable.protobuf.UserProtos.UserListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_UserList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_UserList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.java.world.dante.serializable.protobuf.UserProtos.UserList.class, org.java.world.dante.serializable.protobuf.UserProtos.UserList.Builder.class);
      }

      // Construct using org.java.world.dante.serializable.protobuf.UserProtos.UserList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          userBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.java.world.dante.serializable.protobuf.UserProtos.internal_static_UserList_descriptor;
      }

      @java.lang.Override
      public org.java.world.dante.serializable.protobuf.UserProtos.UserList getDefaultInstanceForType() {
        return org.java.world.dante.serializable.protobuf.UserProtos.UserList.getDefaultInstance();
      }

      @java.lang.Override
      public org.java.world.dante.serializable.protobuf.UserProtos.UserList build() {
        org.java.world.dante.serializable.protobuf.UserProtos.UserList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.java.world.dante.serializable.protobuf.UserProtos.UserList buildPartial() {
        org.java.world.dante.serializable.protobuf.UserProtos.UserList result = new org.java.world.dante.serializable.protobuf.UserProtos.UserList(this);
        int from_bitField0_ = bitField0_;
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            user_ = java.util.Collections.unmodifiableList(user_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.java.world.dante.serializable.protobuf.UserProtos.UserList) {
          return mergeFrom((org.java.world.dante.serializable.protobuf.UserProtos.UserList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.java.world.dante.serializable.protobuf.UserProtos.UserList other) {
        if (other == org.java.world.dante.serializable.protobuf.UserProtos.UserList.getDefaultInstance()) return this;
        if (userBuilder_ == null) {
          if (!other.user_.isEmpty()) {
            if (user_.isEmpty()) {
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserIsMutable();
              user_.addAll(other.user_);
            }
            onChanged();
          }
        } else {
          if (!other.user_.isEmpty()) {
            if (userBuilder_.isEmpty()) {
              userBuilder_.dispose();
              userBuilder_ = null;
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserFieldBuilder() : null;
            } else {
              userBuilder_.addAllMessages(other.user_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.java.world.dante.serializable.protobuf.UserProtos.UserList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.java.world.dante.serializable.protobuf.UserProtos.UserList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.java.world.dante.serializable.protobuf.UserProtos.User> user_ =
        java.util.Collections.emptyList();
      private void ensureUserIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          user_ = new java.util.ArrayList<org.java.world.dante.serializable.protobuf.UserProtos.User>(user_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.java.world.dante.serializable.protobuf.UserProtos.User, org.java.world.dante.serializable.protobuf.UserProtos.User.Builder, org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder> userBuilder_;

      /**
       * <code>repeated .User user = 1;</code>
       */
      public java.util.List<org.java.world.dante.serializable.protobuf.UserProtos.User> getUserList() {
        if (userBuilder_ == null) {
          return java.util.Collections.unmodifiableList(user_);
        } else {
          return userBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public int getUserCount() {
        if (userBuilder_ == null) {
          return user_.size();
        } else {
          return userBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public org.java.world.dante.serializable.protobuf.UserProtos.User getUser(int index) {
        if (userBuilder_ == null) {
          return user_.get(index);
        } else {
          return userBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public Builder setUser(
          int index, org.java.world.dante.serializable.protobuf.UserProtos.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.set(index, value);
          onChanged();
        } else {
          userBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public Builder setUser(
          int index, org.java.world.dante.serializable.protobuf.UserProtos.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.set(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public Builder addUser(org.java.world.dante.serializable.protobuf.UserProtos.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(value);
          onChanged();
        } else {
          userBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public Builder addUser(
          int index, org.java.world.dante.serializable.protobuf.UserProtos.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(index, value);
          onChanged();
        } else {
          userBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public Builder addUser(
          org.java.world.dante.serializable.protobuf.UserProtos.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public Builder addUser(
          int index, org.java.world.dante.serializable.protobuf.UserProtos.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public Builder addAllUser(
          java.lang.Iterable<? extends org.java.world.dante.serializable.protobuf.UserProtos.User> values) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, user_);
          onChanged();
        } else {
          userBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public Builder removeUser(int index) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.remove(index);
          onChanged();
        } else {
          userBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public org.java.world.dante.serializable.protobuf.UserProtos.User.Builder getUserBuilder(
          int index) {
        return getUserFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder getUserOrBuilder(
          int index) {
        if (userBuilder_ == null) {
          return user_.get(index);  } else {
          return userBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public java.util.List<? extends org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder> 
           getUserOrBuilderList() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(user_);
        }
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public org.java.world.dante.serializable.protobuf.UserProtos.User.Builder addUserBuilder() {
        return getUserFieldBuilder().addBuilder(
            org.java.world.dante.serializable.protobuf.UserProtos.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public org.java.world.dante.serializable.protobuf.UserProtos.User.Builder addUserBuilder(
          int index) {
        return getUserFieldBuilder().addBuilder(
            index, org.java.world.dante.serializable.protobuf.UserProtos.User.getDefaultInstance());
      }
      /**
       * <code>repeated .User user = 1;</code>
       */
      public java.util.List<org.java.world.dante.serializable.protobuf.UserProtos.User.Builder> 
           getUserBuilderList() {
        return getUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.java.world.dante.serializable.protobuf.UserProtos.User, org.java.world.dante.serializable.protobuf.UserProtos.User.Builder, org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.java.world.dante.serializable.protobuf.UserProtos.User, org.java.world.dante.serializable.protobuf.UserProtos.User.Builder, org.java.world.dante.serializable.protobuf.UserProtos.UserOrBuilder>(
                  user_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserList)
    }

    // @@protoc_insertion_point(class_scope:UserList)
    private static final org.java.world.dante.serializable.protobuf.UserProtos.UserList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.java.world.dante.serializable.protobuf.UserProtos.UserList();
    }

    public static org.java.world.dante.serializable.protobuf.UserProtos.UserList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserList>
        PARSER = new com.google.protobuf.AbstractParser<UserList>() {
      @java.lang.Override
      public UserList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.java.world.dante.serializable.protobuf.UserProtos.UserList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\032\037google/protobuf/timestamp." +
      "proto\"[\n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022" +
      ",\n\010birthday\030\003 \001(\0132\032.google.protobuf.Time" +
      "stamp\022\013\n\003sex\030\004 \001(\t\"\037\n\010UserList\022\023\n\004user\030\001" +
      " \003(\0132\005.UserB8\n*org.java.world.dante.seri" +
      "alizable.protobufB\nUserProtosP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Birthday", "Sex", });
    internal_static_UserList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserList_descriptor,
        new java.lang.String[] { "User", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
