/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 hnair.com
 * All rights reserved.
 * Date: 2012-10-17
 */
package com.epolleo.bp.forum.action;

import java.util.Date;
import java.util.HashMap;

import javax.annotation.Resource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.alibaba.citrus.service.requestcontext.parser.ParserRequestContext;
import com.alibaba.citrus.turbine.Context;
import com.alibaba.citrus.turbine.dataresolver.Param;
import com.alibaba.citrus.turbine.dataresolver.Params;
import com.alibaba.citrus.turbine.util.Function;
import com.alibaba.citrus.turbine.util.FunctionDir;
import com.alibaba.citrus.turbine.util.FunctionName;

import com.epolleo.bp.forum.bean.ForumGroupBean;
import com.epolleo.bp.forum.dao.ibatis.ForumGroupDao;
import com.epolleo.bp.pub.LoginUser;
import com.epolleo.bp.pub.PagingForm;
import com.epolleo.bp.pub.PagingResult;
import com.epolleo.bp.seq.bean.IdKind;
import com.epolleo.bp.seq.service.SeqService;

/**
 * <p>
 * 论坛版块的Action
 * </p>
 * 
 * Date: 2012-10-17 下午04:17:20
 * 
 * @author Data Model Tool
 * @version 1.0
 */
@Function()
@FunctionDir(id="bp.forumGroup", name="论坛板块")
public class ForumGroupAction {

    protected Logger logger = LoggerFactory.getLogger(getClass());

    @Resource
    private ParserRequestContext parser;

    @Resource
    private SeqService seqService;
    
    @Resource
    private ForumGroupDao forumgroupDao;

    /**
     * 处理指定页及条件的查询结果
     * 
     * @param form
     *            分页参数
     * @param entity
     *            查询过滤参数
     * @see Context
     * @see PagingForm
     * @see ForumGroupBean
     */
    @Function("bp.forumGroup.query")
    @FunctionName("板块查询")
    public void doQuery(Context context, @Params PagingForm form,
        @Params ForumGroupBean entity) {
        HashMap<String, Object> filter = new HashMap<String, Object>();
        Object gpid = entity.getGroupId();
        if (gpid != null) {
            filter.put("groupId", gpid);
        }
        form.setFilterMap(filter);
        PagingResult<ForumGroupBean> result = forumgroupDao.findPaging(form,false);
        context.put("json", result);
    }

    /**
     * @param entity
     *            新增论坛版块对象
     * @see Context
     * @see ForumGroupBean
     */
    @Function("bp.forumGroup.save")
    @FunctionName("板块保存")
    public void doSave(Context context, @Params ForumGroupBean entity) {
        long newTpId = seqService.getNewId(IdKind.GroupId);
        LoginUser lguser = com.epolleo.bp.pub.LoginUser.getCurrentUser();
        entity.setCreaterId(lguser.getUserId());
        entity.setCreaterName(lguser.getUserName());
        entity.setCreateTime(new Date());    
        entity.setUpdateTime(new Date()); 
        entity.setGroupId(newTpId);
        forumgroupDao.save(entity);
        context.put("json", entity);
    }

    /**
     * @param id
     *            待删除论坛版块的关键值（比如主键Key）
     * @see Context
     */
    @Function("bp.forumGroup.delete")
    @FunctionName("板块删除")
    public void doDelete(Context context, @Param(name = "groupId") String id) {
        HashMap<String, Object> result = new HashMap<String, Object>();
        int delete = forumgroupDao.delete(id);
        result.put("success", delete == 1);
        context.put("json", result);
    }

    /**
     * @param entity
     *            修改论坛版块对象
     * @see Context
     * @see ForumGroupBean
     */
    @Function("bp.forumGroup.update")
    @FunctionName("板块更新")
    public void doUpdate(Context context, @Params ForumGroupBean entity) {
        forumgroupDao.update(entity);
        context.put("json", entity);
    }

}