/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 epolleo.com
 * All rights reserved.
 * AnnounceInfoAction.java
 * Date: 2013-01-24
 */
package com.epolleo.bp.announce.bean;

import java.util.Date;
/**
 * <p>通告信息</p>
 * 
 * Date: 2013-01-24 19:10:55
 * 
 * @author TODO
 * @version 1.0
 */
public class AnnounceInfoBean {

    // 编号
    private Long id;
    // 通告内容
    private String content;
    // 生效日期
    private Date effDate;
    // 失效日期
    private Date expDate;
    // 更新人
    private String updateBy;
    // 更新时间
    private Date updateDate;
    //查询结束时间
    private Date announceDateEndQuery;
    //查询开始时间
    private Date announceDate;
    //默认查询前100条
    private String topMark;
    
    private Integer state;
    
    private String funcIds;
    
    private String url;
    
    private String urlName;
    
    private String orgCodes;
    
    public Date getAnnounceDateEndQuery() {
        return announceDateEndQuery;
    }

    public void setAnnounceDateEndQuery(Date announceDateEndQuery) {
        this.announceDateEndQuery = announceDateEndQuery;
    }

    public Date getAnnounceDate() {
        return announceDate;
    }

    public void setAnnounceDate(Date announceDate) {
        this.announceDate = announceDate;
    }

    public String getTopMark() {
        return topMark;
    }

    public void setTopMark(String topMark) {
        this.topMark = topMark;
    }


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取属性content - "通告内容"的值.
     * 
     * @return 返回值是{@link String }
     * @see setContent
     */
    public String getContent() {
        return this.content;
    }

    /**
     * 设置属性content - "通告内容"的值.
     * 
     * @param content 允许传入的值 是{@link String }
     * @see getContent
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 获取属性effDate - "生效日期"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setEffDate
     */
    public Date getEffDate() {
        return this.effDate;
    }

    /**
     * 设置属性effDate - "生效日期"的值.
     * 
     * @param effDate 允许传入的值 是{@link Date }
     * @see getEffDate
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * 获取属性expDate - "失效日期"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setExpDate
     */
    public Date getExpDate() {
        return this.expDate;
    }

    /**
     * 设置属性expDate - "失效日期"的值.
     * 
     * @param expDate 允许传入的值 是{@link Date }
     * @see getExpDate
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * 获取属性updateBy - "更新人"的值.
     * 
     * @return 返回值是{@link String }
     * @see setUpdateBy
     */
    public String getUpdateBy() {
        return this.updateBy;
    }

    /**
     * 设置属性updateBy - "更新人"的值.
     * 
     * @param updateBy 允许传入的值 是{@link String }
     * @see getUpdateBy
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * 获取属性updateDate - "更新时间"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setUpdateDate
     */
    public Date getUpdateDate() {
        return this.updateDate;
    }

    /**
     * 设置属性updateDate - "更新时间"的值.
     * 
     * @param updateDate 允许传入的值 是{@link Date }
     * @see getUpdateDate
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }



    public String getFuncIds() {
        return funcIds;
    }

    public void setFuncIds(String funcIds) {
        this.funcIds = funcIds;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getOrgCodes() {
        return orgCodes;
    }

    public void setOrgCodes(String orgCodes) {
        this.orgCodes = orgCodes;
    }

    public String getUrlName() {
        return urlName;
    }

    public void setUrlName(String urlName) {
        this.urlName = urlName;
    }
}
