/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 hnair.com
 * All rights reserved.
 * ForumGroupAction.java
 * Date: 2012-10-22
 */
package com.epolleo.bp.forum.bean;

import java.util.Date;
/**
 * <p>论坛版块</p>
 * 
 * Date: 2012-10-22 下午02:25:18
 * 
 * @author Data Model Tool
 * @version 1.0
 */
public class ForumGroupBean {

    // 版块ID
    private Long groupId;
    // 版块名称
    private String groupName;
    // 板块描述
    private String groupDesc;
    // 创建者ID
    private String createrId;
    // 创建者姓名
    private String createrName;
    // 禁用标志
    private String disableFlag;
    // 更新时间
    private Date updateTime;
    // 创建时间
    private Date createTime;

    /**
     * 获取属性groupId - "版块ID"的值.
     * 
     * @return 返回值是{@link Long }
     * @see setGroupId
     */
    public Long getGroupId() {
        return this.groupId;
    }

    /**
     * 设置属性groupId - "版块ID"的值.
     * 
     * @param groupId 允许传入的值 是{@link Long }
     * @see getGroupId
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * 获取属性groupName - "版块名称"的值.
     * 
     * @return 返回值是{@link String }
     * @see setGroupName
     */
    public String getGroupName() {
        return this.groupName;
    }

    /**
     * 设置属性groupName - "版块名称"的值.
     * 
     * @param groupName 允许传入的值 是{@link String }
     * @see getGroupName
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * 获取属性groupDesc - "板块描述"的值.
     * 
     * @return 返回值是{@link String }
     * @see setGroupDesc
     */
    public String getGroupDesc() {
        return this.groupDesc;
    }

    /**
     * 设置属性groupDesc - "板块描述"的值.
     * 
     * @param groupDesc 允许传入的值 是{@link String }
     * @see getGroupDesc
     */
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }

    /**
     * 获取属性createrId - "创建者ID"的值.
     * 
     * @return 返回值是{@link String }
     * @see setCreaterId
     */
    public String getCreaterId() {
        return this.createrId;
    }

    /**
     * 设置属性createrId - "创建者ID"的值.
     * 
     * @param createrId 允许传入的值 是{@link String }
     * @see getCreaterId
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId;
    }

    /**
     * 获取属性createrName - "创建者姓名"的值.
     * 
     * @return 返回值是{@link String }
     * @see setCreaterName
     */
    public String getCreaterName() {
        return this.createrName;
    }

    /**
     * 设置属性createrName - "创建者姓名"的值.
     * 
     * @param createrName 允许传入的值 是{@link String }
     * @see getCreaterName
     */
    public void setCreaterName(String createrName) {
        this.createrName = createrName;
    }

    /**
     * 获取属性disableFlag - "禁用标志"的值.
     * 
     * @return 返回值是{@link String }
     * @see setDisableFlag
     */
    public String getDisableFlag() {
        return this.disableFlag;
    }

    /**
     * 设置属性disableFlag - "禁用标志"的值.
     * 
     * @param disableFlag 允许传入的值 是{@link String }
     * @see getDisableFlag
     */
    public void setDisableFlag(String disableFlag) {
        this.disableFlag = disableFlag;
    }

    /**
     * 获取属性updateTime - "更新时间"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setUpdateTime
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置属性updateTime - "更新时间"的值.
     * 
     * @param updateTime 允许传入的值 是{@link Date }
     * @see getUpdateTime
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取属性createTime - "创建时间"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setCreateTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置属性createTime - "创建时间"的值.
     * 
     * @param createTime 允许传入的值 是{@link Date }
     * @see getCreateTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
