/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 hnair.com
 * All rights reserved.
 * ForumTopicAction.java
 * Date: 2012-10-26
 */
package com.epolleo.bp.forum.bean;

import java.util.Date;
/**
 * <p>论坛主题</p>
 * 
 * Date: 2012-10-26 上午10:50:19
 * 
 * @author Data Model Tool
 * @version 1.0
 */
public class ForumTopicBean {

    // 版块ID
    private Long groupId;
    // 主题ID
    private Long topicId;
    // 父主题ID
    private Long parentId;
    // 根主题ID
    private Long rootId;
    // 主题名称
    private String topicName;
    // 主题内容
    private String topicContext;
    // 创建者ID
    private String createrId;
    // 创建者姓名
    private String createrName;
    // 创建时间
    private Date createTime;
    // 叶标志
    private Long isleaf;
    // 回复数
    private Long replycount;

    /**
     * 获取属性groupId - "版块ID"的值.
     * 
     * @return 返回值是{@link Long }
     * @see setGroupId
     */
    public Long getGroupId() {
        return this.groupId;
    }

    /**
     * 设置属性groupId - "版块ID"的值.
     * 
     * @param groupId 允许传入的值 是{@link Long }
     * @see getGroupId
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * 获取属性topicId - "主题ID"的值.
     * 
     * @return 返回值是{@link Long }
     * @see setTopicId
     */
    public Long getTopicId() {
        return this.topicId;
    }

    /**
     * 设置属性topicId - "主题ID"的值.
     * 
     * @param topicId 允许传入的值 是{@link Long }
     * @see getTopicId
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * 获取属性parentId - "父主题ID"的值.
     * 
     * @return 返回值是{@link Long }
     * @see setParentId
     */
    public Long getParentId() {
        return this.parentId;
    }

    /**
     * 设置属性parentId - "父主题ID"的值.
     * 
     * @param parentId 允许传入的值 是{@link Long }
     * @see getParentId
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * 获取属性rootId - "根主题ID"的值.
     * 
     * @return 返回值是{@link Long }
     * @see setRootId
     */
    public Long getRootId() {
        return this.rootId;
    }

    /**
     * 设置属性rootId - "根主题ID"的值.
     * 
     * @param rootId 允许传入的值 是{@link Long }
     * @see getRootId
     */
    public void setRootId(Long rootId) {
        this.rootId = rootId;
    }

    /**
     * 获取属性topicName - "主题名称"的值.
     * 
     * @return 返回值是{@link String }
     * @see setTopicName
     */
    public String getTopicName() {
        return this.topicName;
    }

    /**
     * 设置属性topicName - "主题名称"的值.
     * 
     * @param topicName 允许传入的值 是{@link String }
     * @see getTopicName
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    /**
     * 获取属性topicContext - "主题内容"的值.
     * 
     * @return 返回值是{@link String }
     * @see setTopicContext
     */
    public String getTopicContext() {
        return this.topicContext;
    }

    /**
     * 设置属性topicContext - "主题内容"的值.
     * 
     * @param topicContext 允许传入的值 是{@link String }
     * @see getTopicContext
     */
    public void setTopicContext(String topicContext) {
        this.topicContext = topicContext;
    }

    /**
     * 获取属性createrId - "创建者ID"的值.
     * 
     * @return 返回值是{@link String }
     * @see setCreaterId
     */
    public String getCreaterId() {
        return this.createrId;
    }

    /**
     * 设置属性createrId - "创建者ID"的值.
     * 
     * @param createrId 允许传入的值 是{@link String }
     * @see getCreaterId
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId;
    }

    /**
     * 获取属性createrName - "创建者姓名"的值.
     * 
     * @return 返回值是{@link String }
     * @see setCreaterName
     */
    public String getCreaterName() {
        return this.createrName;
    }

    /**
     * 设置属性createrName - "创建者姓名"的值.
     * 
     * @param createrName 允许传入的值 是{@link String }
     * @see getCreaterName
     */
    public void setCreaterName(String createrName) {
        this.createrName = createrName;
    }

    /**
     * 获取属性createTime - "创建时间"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setCreateTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置属性createTime - "创建时间"的值.
     * 
     * @param createTime 允许传入的值 是{@link Date }
     * @see getCreateTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取属性isleaf - "叶标志"的值.
     * 
     * @return 返回值是{@link Long }
     * @see setIsleaf
     */
    public Long getIsleaf() {
        return this.isleaf;
    }

    /**
     * 设置属性isleaf - "叶标志"的值.
     * 
     * @param isleaf 允许传入的值 是{@link Long }
     * @see getIsleaf
     */
    public void setIsleaf(Long isleaf) {
        this.isleaf = isleaf;
    }

    /**
     * 获取属性replycount - "回复数"的值.
     * 
     * @return 返回值是{@link Long }
     * @see setReplycount
     */
    public Long getReplycount() {
        return this.replycount;
    }

    /**
     * 设置属性replycount - "回复数"的值.
     * 
     * @param replycount 允许传入的值 是{@link Long }
     * @see getReplycount
     */
    public void setReplycount(Long replycount) {
        this.replycount = replycount;
    }

}
