/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 epolleo.com
 * All rights reserved.
 * HolidayAction.java
 * Date: 2013-12-02
 */
package com.epolleo.bp.holiday.bean;

import java.util.Date;
/**
 * <p>节假日管理</p>
 * 
 * Date: 2013-12-02 13:36:49
 * 
 * @author TODO
 * @version 1.0
 */
public class HolidayBean {

    // 假日ID
    private Long hId;
    // 假日日期
    private Date hDate;
    // 假日内容
    private String hContent;
    // 创建人
    private String createUser;
    // 创建时间
    private Date createTime;
    // 更新人
    private String updateUser;
    // 更新时间
    private Date updateTime;
    
    // 日期类型
    private Integer dateType;

    /**
     * 获取属性hId - "假日ID"的值.
     * 
     * @return 返回值是{@link Long }
     * @see setHId
     */
    public Long getHId() {
        return this.hId;
    }

    /**
     * 设置属性hId - "假日ID"的值.
     * 
     * @param hId 允许传入的值 是{@link Long }
     * @see getHId
     */
    public void setHId(Long hId) {
        this.hId = hId;
    }

    /**
     * 获取属性hDate - "假日日期"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setHDate
     */
    public Date getHDate() {
        return this.hDate;
    }

    /**
     * 设置属性hDate - "假日日期"的值.
     * 
     * @param hDate 允许传入的值 是{@link Date }
     * @see getHDate
     */
    public void setHDate(Date hDate) {
        this.hDate = hDate;
    }

    /**
     * 获取属性hContent - "假日内容"的值.
     * 
     * @return 返回值是{@link String }
     * @see setHContent
     */
    public String getHContent() {
        return this.hContent;
    }

    /**
     * 设置属性hContent - "假日内容"的值.
     * 
     * @param hContent 允许传入的值 是{@link String }
     * @see getHContent
     */
    public void setHContent(String hContent) {
        this.hContent = hContent;
    }

    /**
     * 获取属性createUser - "创建人"的值.
     * 
     * @return 返回值是{@link String }
     * @see setCreateUser
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * 设置属性createUser - "创建人"的值.
     * 
     * @param createUser 允许传入的值 是{@link String }
     * @see getCreateUser
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * 获取属性createTime - "创建时间"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setCreateTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置属性createTime - "创建时间"的值.
     * 
     * @param createTime 允许传入的值 是{@link Date }
     * @see getCreateTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取属性updateUser - "更新人"的值.
     * 
     * @return 返回值是{@link String }
     * @see setUpdateUser
     */
    public String getUpdateUser() {
        return this.updateUser;
    }

    /**
     * 设置属性updateUser - "更新人"的值.
     * 
     * @param updateUser 允许传入的值 是{@link String }
     * @see getUpdateUser
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * 获取属性updateTime - "更新时间"的值.
     * 
     * @return 返回值是{@link Date }
     * @see setUpdateTime
     */
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置属性updateTime - "更新时间"的值.
     * 
     * @param updateTime 允许传入的值 是{@link Date }
     * @see getUpdateTime
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getDateType() {
        return dateType;
    }

    public void setDateType(Integer dateType) {
        this.dateType = dateType;
    }
}
