/**
 * This file was generated by Data Model Tool
 * See <a href="http://www.hna.net/dmt/schema">http://www.hna.net/dmt/schema</a>
 *
 * Copyright (c) 2012 epolleo.com
 * All rights reserved.
 * HolidayAction.java
 * Date: 2013-12-02
 */
package com.epolleo.bp.holiday.bean;

import java.util.Date;
import java.util.List;
/**
 * <p>节假日保存Bean</p>
 * 
 * Date: 2013-12-02 13:36:49
 * 
 * @author TODO
 * @version 1.0
 */
public class HolidaySaveBean {

    private Integer year;
    private Integer month;
    // 节假日
    private String strDays;
    // 工作日
    private String wkDays;
    private List<HolidayBean> days;
    // 更新人
    private String updateUser;
    // 更新时间
    private Date updateTime;
    
    public Integer getYear() {
        return year;
    }
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getMonth() {
        return month;
    }
    public void setMonth(Integer month) {
        this.month = month;
    }
    public List<HolidayBean> getDays() {
        return days;
    }
    public void setDays(List<HolidayBean> days) {
        this.days = days;
    }
    public String getStrDays() {
        return strDays;
    }
    public void setStrDays(String strDays) {
        this.strDays = strDays;
    }
    public String getUpdateUser() {
        return updateUser;
    }
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    public Date getUpdateTime() {
        return updateTime;
    }
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    public String getWkDays() {
        return wkDays;
    }
    public void setWkDays(String wkDays) {
        this.wkDays = wkDays;
    }
}
